#!/bin/bash
# Decrypt all ansible vault files
for i in $(find . -name vault.y*ml); do ansible-vault decrypt $i  --vault-password-file ~/.vault && echo $i decrypted ; done
for i in $(find . -name *.tfvars); do ansible-vault decrypt $i  --vault-password-file ~/.vault && echo $i decrypted ; done