---
- name: Listen for events on a webhook
  hosts: all
  ## Define our source for events
  sources:
    - ansible.eda.webhook: # Please refer to https://github.com/ansible/event-driven-ansible/blob/main/extensions/eda/plugins/event_source/webhook.py
        host: 0.0.0.0
        port: 5000
        certfile: ./misc/certgenerator/dotOcean-test.crt
        keyfile: ./misc/certgenerator/dotOcean-test.key
        # password: "Test123"
  ## Define the conditions we are looking for
  rules:
    # NOTE: This doesn't handle IP address changes, it only "sees" addition or removal of interfaces
    - name: Deploy a VM to the ProxMox Cluster
      condition: >-
        event.payload.snapshots.postchange.tags contains "terraform" and
        event.payload.model == "virtualmachine" and
        event.payload.data.cluster.name == "ProxMox_staging" and
        (
        (event.payload.event == "updated" and
        (event.payload.snapshots.prechange.description != event.payload.snapshots.postchange.description or
        event.payload.snapshots.prechange.vcpus != event.payload.snapshots.postchange.vcpus or
        event.payload.snapshots.prechange.memory != event.payload.snapshots.postchange.memory))
        or
        (event.payload.data.cluster.name == "ProxMox_staging" and
        event.payload.snapshots.prechange.tags not contains "terraform" and
        event.payload.snapshots.postchange.tags contains "terraform"))
      action:
        run_playbook:
          name: ../playbooks/vm-deploy.yml


    # NOTE: This DOES handle IP address changes
    - name: Update VM IP address
      condition: >-
        event.payload.snapshots.postchange.tags contains "terraform" and
        event.payload.model == "ipaddress" and
        event.payload.event == "updated" and
        ((event.payload.snapshots.postchange.address != event.payload.snapshots.prechange.address and event.payload.snapshots.postchange.status == "dhcp") or
        event.payload.snapshots.postchange.status != event.payload.snapshots.prechange.status)
      action:
        run_playbook:
          name: ../playbooks/vm-change-ip.yml

    # NOTE: Zabbix installation and configuration won’t be done,
    # since it takes too much time for the playbooks to complete
    - name: Install Zabbix on a VM in the ProxMox Cluster
      condition: >-
        event.payload.snapshots.postchange.tags contains "terraform" and
        event.payload.data.cluster.name == "ProxMox_staging" and
        event.payload.snapshots.postchange.primary_ip4 != "null" and
        (event.payload.event == "updated" and
        (event.payload.snapshots.prechange.tags != event.payload.snapshots.postchange.tags and
        event.payload.snapshots.prechange.tags not contains "zabbix" and
        event.payload.snapshots.postchange.tags contains "zabbix"))
      action:
        debug:
          msg: "Installing Zabbix!"

    - name: Remove Zabbix from a VM in the ProxMox Cluster
      condition: >-
        event.payload.snapshots.postchange.tags contains "terraform" and
        event.payload.data.cluster.name == "ProxMox_staging" and
        event.payload.snapshots.postchange.primary_ip4 != "null" and
        (event.payload.event == "updated" and
        (event.payload.snapshots.prechange.tags != event.payload.snapshots.postchange.tags and
        event.payload.snapshots.prechange.tags contains "zabbix" and
        event.payload.snapshots.postchange.tags not contains "zabbix"))
      action:
        debug:
          msg: "Removing Zabbix!"

# sources:
# https://ansible.readthedocs.io/projects/rulebook/en/stable/conditions.html#check-if-an-item-exists-in-a-list

# Start this rulebook
# ansible-rulebook -r webhook.yml -i ../inventories

# Known issues (netbox)
# https://github.com/netbox-community/netbox/issues/15387
