---
- name: Listen for events on a webhook
  hosts: all
  ## Define our source for events  ## Define our source for events
  sources:
    - ansible.eda.webhook: # Please refer to https://github.com/ansible/event-driven-ansible/blob/main/extensions/eda/plugins/event_source/webhook.py
        host: 0.0.0.0
        port: 5000
        certfile: ./misc/certgenerator/dotOcean-test.crt
        keyfile: ./misc/certgenerator/dotOcean-test.key
        # password: "Test123"
  ## Define the conditions we are looking for
  rules:
    - name: Deploy a VM to the ProxMox Cluster
      condition: >-
        (event.payload.data.cluster.name == "ProxMox_staging" and
        (event.payload.snapshots.postchange.tags contains "terraform" and
        event.payload.snapshots.prechange.tags not contains "terraform"))

      action:
        debug:
          msg: "Bonjour!"
