---
- name: Listen for events on a webhook
  hosts: all
  ## Define our source for events
  sources:
    - ansible.eda.url_check:
        urls:
          - http://localhost:8000
      # delay: 10
  rules:
    # Define the conditions we are looking for
    - name: Web site is up
      condition: event.url_check.status == "up"
    ## Define the action we should take should the condition be met
      action:
        run_module:
          name: ansible.builtin.debug
          module_args:
            msg: "Web site is up, nice!"

    - name: Web site is down
      condition:
        all:
          - event.url_check.status == "down"
      action:
        run_playbook:
          name: yahoo.yml

# Start a minimal webserver
# python3 -m http.server
